name: Test on Linux

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Run install.sh
        run: |
          set -e
          export CI=1
          git submodule update --init
          bash install.sh
